import 'dart:io';

import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../data/models/miner.dart';
import '../../data/models/miner_snapshot.dart';

class PdfExporter {
  static final _dateFormat = DateFormat('yyyy-MM-dd_HH-mm-ss');
  static final _displayDateFormat = DateFormat('MMM d, yyyy HH:mm');
  static final _tableTimeFormat = DateFormat('MM/dd HH:mm');

  static const int _maxTableRows = 500;

  // Bitcoin orange
  static const _primaryColor = PdfColor.fromInt(0xFFF7931A);
  static const _textSecondary = PdfColor.fromInt(0xFF8B949E);

  /// Generate a PDF report. Returns the file path.
  static Future<String> exportToFile(
    Miner miner,
    List<MinerSnapshot> snapshots,
  ) async {
    final pdf = pw.Document(
      theme: pw.ThemeData.withFont(),
    );

    final sortedSnapshots = List<MinerSnapshot>.from(snapshots)
      ..sort((a, b) => a.timestamp.compareTo(b.timestamp));

    final summary = _buildSummary(sortedSnapshots);
    final tableData = _prepareTableData(sortedSnapshots);

    final dateRange = sortedSnapshots.isEmpty
        ? 'No data'
        : '${_displayDateFormat.format(sortedSnapshots.first.timestamp)} - '
            '${_displayDateFormat.format(sortedSnapshots.last.timestamp)}';

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(miner, dateRange, context),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          _buildSummarySection(summary),
          pw.SizedBox(height: 20),
          if (tableData.isNotEmpty) _buildDataTable(tableData),
          if (sortedSnapshots.length > _maxTableRows)
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 8),
              child: pw.Text(
                'Note: Data downsampled from ${sortedSnapshots.length} '
                'to $_maxTableRows rows for readability.',
                style: const pw.TextStyle(
                  fontSize: 8,
                  color: _textSecondary,
                ),
              ),
            ),
        ],
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final safeName = miner.name.replaceAll(RegExp(r'[^\w\-]'), '_');
    final dateStr = _dateFormat.format(DateTime.now());
    final filename = 'mineviewer_${safeName}_$dateStr.pdf';
    final file = File('${dir.path}/$filename');

    await file.writeAsBytes(await pdf.save());
    return file.path;
  }

  static pw.Widget _buildHeader(
    Miner miner,
    String dateRange,
    pw.Context context,
  ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'MineViewer Report',
              style: pw.TextStyle(
                fontSize: 20,
                fontWeight: pw.FontWeight.bold,
                color: _primaryColor,
              ),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 9, color: _textSecondary),
            ),
          ],
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          '${miner.name}  |  ${miner.type.displayName}'
          '${miner.model != null ? "  |  ${miner.model}" : ""}',
          style: const pw.TextStyle(fontSize: 11, color: _textSecondary),
        ),
        pw.Text(
          dateRange,
          style: const pw.TextStyle(fontSize: 9, color: _textSecondary),
        ),
        pw.SizedBox(height: 8),
        pw.Divider(color: _primaryColor, thickness: 0.5),
        pw.SizedBox(height: 12),
      ],
    );
  }

  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Column(
      children: [
        pw.Divider(color: _textSecondary, thickness: 0.25),
        pw.SizedBox(height: 4),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by MineViewer',
              style: const pw.TextStyle(fontSize: 8, color: _textSecondary),
            ),
            pw.Text(
              _displayDateFormat.format(DateTime.now()),
              style: const pw.TextStyle(fontSize: 8, color: _textSecondary),
            ),
          ],
        ),
      ],
    );
  }

  static _SummaryData _buildSummary(List<MinerSnapshot> snapshots) {
    if (snapshots.isEmpty) {
      return _SummaryData(
        avgHashrate: 0,
        avgTemp: 0,
        avgPower: 0,
        avgEfficiency: 0,
        totalUptimeHours: 0,
        snapshotCount: 0,
      );
    }

    double sumHashrate = 0;
    double sumTemp = 0;
    int tempCount = 0;
    double sumPower = 0;
    int powerCount = 0;
    double sumEfficiency = 0;
    int efficiencyCount = 0;

    for (final s in snapshots) {
      sumHashrate += s.hashrate;
      if (s.asicTemp != null) {
        sumTemp += s.asicTemp!;
        tempCount++;
      }
      if (s.power != null) {
        sumPower += s.power!;
        powerCount++;
      }
      if (s.efficiency != null) {
        sumEfficiency += s.efficiency!;
        efficiencyCount++;
      }
    }

    final lastUptime = snapshots.last.uptimeSeconds ?? 0;

    return _SummaryData(
      avgHashrate: sumHashrate / snapshots.length,
      avgTemp: tempCount > 0 ? sumTemp / tempCount : 0,
      avgPower: powerCount > 0 ? sumPower / powerCount : 0,
      avgEfficiency: efficiencyCount > 0 ? sumEfficiency / efficiencyCount : 0,
      totalUptimeHours: lastUptime / 3600.0,
      snapshotCount: snapshots.length,
    );
  }

  static pw.Widget _buildSummarySection(_SummaryData summary) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: _textSecondary, width: 0.5),
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Summary',
            style: pw.TextStyle(
              fontSize: 13,
              fontWeight: pw.FontWeight.bold,
              color: _primaryColor,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              _summaryItem(
                'Avg Hashrate',
                _formatHashrate(summary.avgHashrate),
              ),
              _summaryItem(
                'Avg Temp',
                '${summary.avgTemp.toStringAsFixed(1)} C',
              ),
              _summaryItem(
                'Avg Power',
                '${summary.avgPower.toStringAsFixed(1)} W',
              ),
              _summaryItem(
                'Avg Efficiency',
                '${summary.avgEfficiency.toStringAsFixed(1)} J/TH',
              ),
              _summaryItem(
                'Uptime',
                '${summary.totalUptimeHours.toStringAsFixed(1)} hrs',
              ),
            ],
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            '${summary.snapshotCount} data points',
            style: const pw.TextStyle(fontSize: 8, color: _textSecondary),
          ),
        ],
      ),
    );
  }

  static pw.Widget _summaryItem(String label, String value) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          label,
          style: const pw.TextStyle(fontSize: 8, color: _textSecondary),
        ),
        pw.SizedBox(height: 2),
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 11,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
      ],
    );
  }

  static List<List<String>> _prepareTableData(List<MinerSnapshot> snapshots) {
    List<MinerSnapshot> data;
    if (snapshots.length > _maxTableRows) {
      // Downsample: pick evenly-spaced indices
      final step = snapshots.length / _maxTableRows;
      data = List.generate(
        _maxTableRows,
        (i) => snapshots[(i * step).floor().clamp(0, snapshots.length - 1)],
      );
    } else {
      data = snapshots;
    }

    return data.map((s) {
      return [
        _tableTimeFormat.format(s.timestamp),
        _formatHashrate(s.hashrate),
        s.asicTemp != null ? s.asicTemp!.toStringAsFixed(1) : '-',
        s.power != null ? s.power!.toStringAsFixed(1) : '-',
        s.efficiency != null ? s.efficiency!.toStringAsFixed(1) : '-',
      ];
    }).toList();
  }

  static pw.Widget _buildDataTable(List<List<String>> rows) {
    const headers = ['Time', 'Hashrate', 'Temp (C)', 'Power (W)', 'Eff (J/TH)'];

    return pw.TableHelper.fromTextArray(
      headers: headers,
      data: rows,
      headerStyle: pw.TextStyle(
        fontSize: 8,
        fontWeight: pw.FontWeight.bold,
        color: _primaryColor,
      ),
      cellStyle: const pw.TextStyle(fontSize: 7),
      headerDecoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(color: _primaryColor, width: 0.5),
        ),
      ),
      cellAlignments: {
        0: pw.Alignment.centerLeft,
        1: pw.Alignment.centerRight,
        2: pw.Alignment.centerRight,
        3: pw.Alignment.centerRight,
        4: pw.Alignment.centerRight,
      },
      cellPadding: const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 2),
    );
  }

  static String _formatHashrate(double hashrateHs) {
    if (hashrateHs >= 1e12) {
      return '${(hashrateHs / 1e12).toStringAsFixed(2)} TH/s';
    } else if (hashrateHs >= 1e9) {
      return '${(hashrateHs / 1e9).toStringAsFixed(2)} GH/s';
    } else if (hashrateHs >= 1e6) {
      return '${(hashrateHs / 1e6).toStringAsFixed(2)} MH/s';
    } else if (hashrateHs >= 1e3) {
      return '${(hashrateHs / 1e3).toStringAsFixed(2)} KH/s';
    }
    return '${hashrateHs.toStringAsFixed(2)} H/s';
  }
}

class _SummaryData {
  final double avgHashrate;
  final double avgTemp;
  final double avgPower;
  final double avgEfficiency;
  final double totalUptimeHours;
  final int snapshotCount;

  _SummaryData({
    required this.avgHashrate,
    required this.avgTemp,
    required this.avgPower,
    required this.avgEfficiency,
    required this.totalUptimeHours,
    required this.snapshotCount,
  });
}
